on:
  push:
    branches:
      - deploy

name: Deploy main branch to Chalice
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: chalice deploy
      uses: 5tigerjelly/chalice-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CHALICE_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CHALICE_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
